version: "3.8"

services:
  db:
    image: postgres:15
    container_name: skillswap_postgres
    restart: always
    environment:
      POSTGRES_USER: Code01
      POSTGRES_PASSWORD: Code01
      POSTGRES_DB: skillswap_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

